module.exports.User = require("./user.model");
module.exports.Category = require("./category.model");
module.exports.Bus=require("./bus.model");
module.exports.Hotel=require("./hotel.model")
module.exports.Stationery=require("./stationery.model");
module.exports.School=require("./school.model");
module.exports.Travel=require("./travel.model");
module.exports.Pharmacy=require("./pharmacy.model");
module.exports.Jewelry=require("./jewelry.model");
module.exports.Movie=require("./movie.model");
module.exports.Music=require("./music.model");
module.exports.grocery=require("./grocery.model");
